### PR TITLE
(MAINT) Release prep for 2.4.0

### PR DESCRIPTION
**Pull request by scotje**

### CODE REVIEW

**Comment by kris-bosland** [comment]
Tests failed with `NameError: uninitialized constant BoltSpec`, I assume something changed out from under us?

**Comment by scotje** [comment]
> Tests failed with `NameError: uninitialized constant BoltSpec`, I assume something changed out from under us?

Yeah, I think @glennsarti is working on a fix.

**Comment by scotje** [comment]
Looks like Glenn's fix is waiting on this litmus PR: https://github.com/puppetlabs/puppet_litmus/pull/248

**Comment by glennsarti** [comment]
TBH it's probably safe to release without the litmus stuff running if it's urgent.

**Comment by glennsarti** [comment]
Workaround PR in #222.  Rekicking this PR.

**Comment by glennsarti** [comment]
Needs rebase onto master.

**Pull request merged**
