### PR TITLE
(GH-225) Document functions in Puppet Datatypes

### LINKED ISSUE #225: [Feature] Document functions in Puppet Datatypes
## Use Case
In Pull Request https://github.com/puppetlabs/puppet-strings/pull/199 only Datatype attributes were added.  Datatype functions should also be documented

## Describe the Solution You Would Like
Puppet-strings should document data type functions like a regular function

## Describe Alternatives You've Considered
N/A

## Additional Context
The Bolt core libraries use functions e.g.
https://github.com/puppetlabs/bolt/blob/master/bolt-modules/boltlib/lib/puppet/datatypes/target.rb

### PR DESCRIPTION
**Pull request by glennsarti**
Fixes #225 

Previously the puppet datatype handler only documented attributes, not functions
for example [1].  This commit updates the data type handler to read in the
function information and then allow that to be used by puppet-strings in its
JSON, Markdown and HTML renderers.  This commit also adds tests for many
different scenarios and all three rendering types.

[1] https://github.com/puppetlabs/puppet/blob/3e03e734dda415272ec156b03ed9f021ba243228/lib/puppet/datatypes/error.rb#L13-L15

---

- [x] Actually read functions in datatypes
- [x] unit tests for handler
- [x] Add output support (HTML pending)
- [x] Test with multiple interface definitions
- [x] Tests for JSON output
- [x] Tests for markdown output
- [x] Tests for HTML output?

### CODE REVIEW

**Comment by glennsarti** [comment]
Example HTML output

image

**Comment by glennsarti** [comment]
@binford2k @scotje Can I get a review (and merge) on this?

**Comment by glennsarti** [comment]
Unfortunately `methods` is a method name on Object so you can't use it :-(  Thus YARD uses meth and methds

```
[1] pry(main)> t-editor-services [add-tests-for-puppetfile ≡]> be pry
[5] pry(main)> $x = '12345'
=> "12345"
[6] pry(main)> $x.methods
=> [:shellsplit,
 :encode,
 :include?,
 :%,
 :*,
 :+,
 :to_c,
 :count,
 :partition,
 :sum,
```

**Comment by eputnam** [comment]
oh duh, sorry. as you were.

**Pull request merged**
