### PR TITLE
(MAINT) Drop Ruby 2.1.x and Puppet 4.x compatibility

### PR DESCRIPTION
**Pull request by scotje**

### CODE REVIEW

**Comment by scotje** [comment]
ping @binford2k 

This would end up being at least a .Y release bump, possibly a major.

**Comment by binford2k** [comment]
This is one hell of a PR! As far as I can tell, it doesn't affect any functionality and just appeases the rubocops. 👍

**Review by binford2k — APPROVED** [review]

**Comment by binford2k** [comment]
Do we want to get #252 in this release?

**Review by sanfrancrisko — APPROVED** [review]

**Comment by daianamezdrea** [comment]
Hi guys, if everyone agrees, this PR LGTM and will be merged! Thank you all for your contributions ! Cheers!

**Pull request merged**
