### PR TITLE
Test against specific, supported versions of Puppet

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
The failing tests are rubocop errors. Since these are a matter of style, should they be fixed or added to the list of ignored cops?

For quick reference, see https://travis-ci.org/puppetlabs/puppet-strings/jobs/170334697

**Comment by ghoneycutt** [comment]
rubocop moves fast, when I initially checked with v0.41.2, as opposed to the current v0.44.1, the style was fine.

**Comment by whopper** [comment]
Thanks @ghoneycutt! I'd vote for adding those two to the list of ignored cops, personally.

**Comment by ghoneycutt** [comment]
Ignoring those two as @whopper suggested.

**Comment by whopper** [comment]
Thanks @ghoneycutt, looks good and travis is happy! Last nitpick: would you mind adding `(maint)` to the beginning of your two commit messages? Helps with releasing down the line.

**Comment by ghoneycutt** [comment]
@whopper rebased

**Comment by whopper** [comment]
👍 wewt, once travis is green i'll click the button

**Comment by ghoneycutt** [comment]
Thank you

**Pull request merged**
