### PR TITLE
Improved markdown templates

### PR DESCRIPTION
**Pull request by kozl**
- Added parameter list for classes, defines, data types and resource types with links to detailed parameter description. Useful for classes that have lots of parameters
- Fixed anchor links in markdown templates — original ones didn't work at Bitbucket

### CODE REVIEW

**Comment by binford2k** [comment]
@kozl Thanks for the PR! 🥳 

Could you break this into two separate commits? One to add the parameter lists and one to add the anchors. This makes it easier to revert either of those if we ever need to.

Can you take a look at the failing tests? It looks like the templates are not compiling properly.

**Comment by kozl** [comment]
Yeah, sure! I'll come back a little bit later with that

**Comment by kozl** [comment]
Forgot another thing: I've fixed how data types aliases are displayed. They get unreadable for large data types:
https://www.imageupload.net/image/4KjFb

Broke all changes in separete commits and fixed tests

**Review by binford2k — APPROVED** [review]

**Comment by kozl** [comment]
Who is going to merge this? I don't have permissions

**Comment by binford2k** [comment]
@kozl we do a biweekly Tuesday triage & review. Next one is a week from today.

**Review by sanfrancrisko — APPROVED** [review]

**Comment by daianamezdrea** [comment]
Hi @kozl, this looks good! Thank you for your contribution! Cheers!

**Pull request merged**
