### PR TITLE
Drop support for old releases

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by Magisus** [comment]
Should this also include entries for Puppet 5/Ruby 2.4.1?

**Comment by Magisus** [comment]
Does this supersede #143 ?

**Comment by ghoneycutt** [comment]
Hi @Magisus 

This does supercede PR #143.

It does not include Puppet 5 / Ruby 2.4.1 as that was not already supported.

It does not include ruby 2.3.3 as that was never a supported Ruby version by Puppet.

**Comment by Magisus** [comment]
Alright. In that case this looks fine to me. Shall I close the other one and merge this one?

**Pull request merged**
