### PR TITLE
Pin yard to ~> 0.8.7 in gemspec to match Gemfile

### PR DESCRIPTION
**Pull request by 3flex**
https://github.com/puppetlabs/puppetlabs-strings/pull/91 introduced the Gemfile change

### CODE REVIEW

**Comment by 3flex** [comment]
Possibly this should be removed from Gemfile as well, since Gemfile already includes `gemspec`

**Comment by iankronquist** [comment]
@3flex I think Rubocop was upgraded and now only supports Ruby 2.0.0, so the Travis CI tests are failing. I bet if you pinned rubocop to an older version the tests would pass.
https://github.com/puppetlabs/puppetlabs-strings/blob/master/Gemfile#L22

**Comment by kylog** [comment]
Ah yeah, @iankronquist is right (hi Ian!): rubocop 0.42 dropped support for ruby < 2.0. A couple projects I'm involved with have been bitten by that one.

PR for that bit incoming ....

**Comment by kylog** [comment]
https://github.com/puppetlabs/puppetlabs-strings/pull/97

**Comment by peterhuene** [comment]
Hi @3flex, could you rebase your branch on current master to pick up @kylog's fix?  Thanks!

**Comment by 3flex** [comment]
Done!

**Comment by 3flex** [comment]
I do wonder (again) if this should be removed from Gemfile, so these don't get out of sync again...

**Comment by 3flex** [comment]
Close https://tickets.puppetlabs.com/browse/PDOC-51 once this has been merged?

**Comment by peterhuene** [comment]
Hi @3flex.  Thanks again for this contribution.  We've recently merged in a major refactoring work for Puppet Strings that moves to the latest version of the Yard gem.  Your fix was taken into account and now both the Gemfile and gemspec have the same specifier.

As such, I'm closing this PR now that the refactoring work has been merged.  Please re-open if you have any questions or concerns.  Thanks!

**Pull request closed without merging**
