### PR TITLE
Add deprecated tag

### LINKED ISSUE #339: Please add support for deprecated tag
## Use Case
I [recently tried](https://github.com/voxpupuli/puppet-dnsquery/pull/126#pullrequestreview-1303074204) to use the [deprecated](https://www.rubydoc.info/gems/yard/file/docs/Tags.md#deprecated) yard tag hoping that this would create some type of deprecated label on the resulting documentation however as far as i can tell it had no affect.  Could we please add support for the deprecated tag.

## Describe the Solution You Would Like
When using the `@deprecated` tag mark functions in the resulting documentation with a deprecated header e.g.

```ruby
# some function
Puppet::Functions.create_function(:deprecated_function) do
  # @deprecated this function causes issues
 ...
end
```
should result in something like 

```
### <a name="deprecated_function"></a>`deprecated_function`

Type: Ruby 4.x API

[DEPRECATD]  this function causes issues

some function
...
```

### PR DESCRIPTION
**Pull request by b4ldr**
I had a stab at adding the deprecated flag

Fixes #339

### CODE REVIEW

**Comment by chelnak** [comment]
This looks good and tests are passing.

Just one thing I noticed that we can maybe tidy up.

The description being used for deprecated is "Use a something else".

Could you possibly change the message a bit so it's more relevant to the deprecation of something and a little softer?

Maybe along the lines of "no longer supported and will be removed in a future release".

Thanks!

**Comment by b4ldr** [comment]
thanks for the comments

> Maybe along the lines of "no longer supported and will be removed in a future release".
done

**Comment by chelnak** [comment]
Looks like you have a couple of rubocop violations to clear up.

Once they are done I'm happy to get this merged!

**Comment by b4ldr** [comment]
updated hopefully all green now

**Review by chelnak — APPROVED** [review]

**Comment by chelnak** [comment]
@b4ldr Thank you!

**Pull request merged**
